### ISSUE TITLE
site hasn't been deployed

### ISSUE THREAD

**Issue by Haroenv** [react-boilerplate/site#15]
I think something went wrong with the "building" of the site to `gh-pages`, since the last commit there was in february, and online I see #13 still being to the wrong link.

Maybe check travis logs?

something like [gh-pages-travis](https://github.com/pghalliday/gh-pages-travis) could be used to automate it.

**Comment by brotzky** [comment]
The link in the footer is correctly deployed; closing this issue.
https://www.reactboilerplate.com/
